services:
  # SentientCore True AGI
  agi:
    build:
      context: .
      dockerfile: deploy/Dockerfile.simple
    container_name: agi-bleujs-agi
    restart: unless-stopped
    ports:
      - "127.0.0.1:8080:8080"
    environment:
      - NODE_ENV=production
      - PORT=8080
      - DOMAIN=agi.bleujs.org
    networks:
      - agi-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Nginx Reverse Proxy for AGI subdomain
  nginx:
    image: nginx:alpine
    container_name: agi-bleujs-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./deploy/agi-bleujs-nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - agi
    networks:
      - agi-network
    healthcheck:
      test: ["CMD", "nginx", "-t"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  agi-network:
    driver: bridge 